#!/usr/bin/perl

`mkdir bin/proteus`;
`mkdir bin/proteus/analytics`;

`mkdir bin/proteus/dl`;
`mkdir bin/proteus/dl/parser`;
`mkdir bin/proteus/dl/syntax`;
`mkdir bin/proteus/dl/semantics`;

`mkdir bin/proteus/externaltools`;
`mkdir bin/proteus/externaltools/matlabscriptingkit`;

`mkdir bin/proteus/logicsolvers`;
`mkdir bin/proteus/logicsolvers/abstractions`;
`mkdir bin/proteus/logicsolvers/mathematicakit`;

#`mkdir bin/proteus/tests`;

# Compile
`cd src/dl/parser; jflex dLLexer.lex; bison dLParser.y`;
#`cd \$PROTEUS/src/dl/semantics; ./GenerateNativeInterpretation`;
`cd src; javac logicsolvers/abstractions/*.java logicsolvers/mathematicakit/*.java dl/parser/*.java dl/syntax/*.java dl/semantics/*.java externaltools/matlabscriptingkit/*.java`;

# Organize
`cp -R src/externaltools/matlabscriptingkit/*.class bin/manticore/externaltools/matlabscriptingkit`;
#`mv src/*.class bin;`;

`mv src/dl/parser/*.class bin/proteus/dl/parser/`;
`mv src/dl/syntax/*.class bin/proteus/dl/syntax/`;
`mv src/dl/semantics/*.class bin/proteus/dl/semantics/`;


`mv src/logicsolvers/abstractions/*.class bin/proteus/logicsolvers/abstractions/`;
`mv src/logicsolvers/mathematicakit/*.class bin/proteus/logicsolvers/mathematicakit/`;

`mv src/externaltools/matlabscriptingkit/*.class bin/proteus/externaltools/matlabscriptingkit/`;
#`mv src/analytics/*.class bin/proteus/analytics/`;
#`mv src/tests/*.class bin/proteus/tests/`;

`cd bin; jar -cf proteus.jar proteus/*`;

